name: MDFPvP
main: se.shard.kaustic.mdfpvp.MDFPvP
version: 0.2.0-pre
author: Johan Haegg
database: true
description: >
             PvP Plugin for MDF Minecraft Server
             
commands:
  claim:
    description: Claims the current chunk.
    permission: mdfpvp.mechanics.claim
    
  removeclaim: 
    description: Removes the claim the player is standing on.
    permission: mdfpvp.mechanics.removeclaim    
    
  setxp:
    description: Sets the total xp of the player
    permission: mdfpvp.admin.setxp
    
permissions:

  mdfpvp.mechanics.*:
    description: Gives access to all basic player mechanics.
    children:
      mdfpvp.mechanics.claim: true
      mdfpvp.mechanics.removeclaim: true

  mdfpvp.mechanics.claim:
    description: Allows user to claim a chunk.
    default: true

  mdfpvp.mechanics.removeclaim:
    description: Allows user to remove a claim.
    default: true

  mdfpvp.admin.*:
    description: Gives access to all administrator commands.
    children:
      mdfpvp.admin.setxp: true
      mdfpvp.admin.removeclaim: true
      
  mdfpvp.admin.setxp:
    description: Allows the user to set the total xp of a player.
    default: op
  
  mdfpvp.admin.removeclaim:
    description: Allows the user to remove any claim.
    default: op